package smile.classification {
  interface Classifier<T>
  
  class DecisionTree 
  class SVM<T>
  class "MLP" as MLPc
  class KNN<T>
  
  Classifier <|-- SVM
  Classifier <|-- MLPc
  Classifier <|-- KNN
  Classifier <|-- DecisionTree
}

package java.util.function {
  interface ToDoubleFunction<T>
}

package smile.regression {
  interface Regression<T>
  
  class RegressionTree 
  class "MLP" as MLPr
  class "KernelMachine<T>" as KMr
  
  Regression <|-- RegressionTree
  Regression <|-- MLPr
  Regression <|-- KMr
}

Classifier -right-|>  ToDoubleFunction
Regression -left-|>  ToDoubleFunction

'smile.classification -[hidden]right- java.util.function
'java.util.function -[hidden]right- smile.regression