@startuml
package smile.classification {
  interface Classifier<T>

  class DecisionTree
  class SVM<T>
  class "MLP" as MLPc
  class KNN<T>

  Classifier <|-- SVM
  Classifier <|-- MLPc
  Classifier <|-- KNN
  Classifier <|-- DecisionTree
}

package java.util.function {
  interface ToDoubleFunction<T>
}

package smile.regression {
  interface Regression<T>

  class RegressionTree
  class "MLP" as MLPr
  class "KernelMachine<T>" as KMr

  Regression <|-- RegressionTree
  Regression <|-- MLPr
  Regression <|-- KMr
}

Classifier -right-|>  ToDoubleFunction
Regression -left-|>  ToDoubleFunction

'smile.classification -[hidden]right- java.util.function
'java.util.function -[hidden]right- smile.regression

package smile.data {
  interface DataFrame
  interface Tuple
  interface StructType

  DataFrame "1" o-- "1" StructType
  DataFrame "0" *-- "N" Tuple
}

package smile.validation {
  interface CrossValidation

  interface ClassificationMetric
  interface RegressionMetric

  ClassificationMetric <|-- Accuracy
  ClassificationMetric <|-- FScore

  RegressionMetric <|-- MSE
  RegressionMetric <|-- R2
}

package smile.feature {
  interface FeatureTransform

  FeatureTransform <|-- Normalizer
  FeatureTransform <|-- Scaler
  FeatureTransform <|-- Standardizer
}
@enduml
